version: '3.4'

services:
  postgresql:
    image: "postgres:latest"
    ports:
     - "5432:5432"
    environment:
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 9080:8080

